import { Gig, MmfFund, FinancialLog, User, ServiceSubscriptionMetric } from '../types';

export const INITIAL_USER: User = {
  id: 'usr-mmu-04289',
  phoneNumber: '254712345678',
  fullName: 'Brian Kiprono',
  campus: 'MMU',
  isVerified: true,
  createdAt: '2026-09-01T08:00:00Z',
  subscribedService: '1-Semester All-Access Pass',
  subscriptionStatus: 'ACTIVE',
};

export const INITIAL_STUDENT_ACCOUNTS: User[] = [
  {
    id: 'usr-mmu-04289',
    phoneNumber: '254712345678',
    fullName: 'Brian Kiprono',
    campus: 'MMU',
    isVerified: true,
    createdAt: '2026-09-01T08:00:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-uon-08124',
    phoneNumber: '254722987654',
    fullName: 'Wanjiku Kamau',
    campus: 'UoN',
    isVerified: true,
    createdAt: '2026-09-03T11:20:00Z',
    subscribedService: 'AI Screening Prompts & Guides',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-jkuat-01938',
    phoneNumber: '254701239841',
    fullName: 'Dennis Omondi',
    campus: 'JKUAT',
    isVerified: true,
    createdAt: '2026-09-05T14:15:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-ku-05712',
    phoneNumber: '254798334455',
    fullName: 'Mercy Jebet',
    campus: 'KU',
    isVerified: false,
    createdAt: '2026-09-08T09:40:00Z',
    subscribedService: 'SMS Statement Sync & PDF Exporter',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-strath-02381',
    phoneNumber: '254740112233',
    fullName: 'Farouk Hassan',
    campus: 'Strathmore',
    isVerified: true,
    createdAt: '2026-09-10T16:50:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-egerton-03910',
    phoneNumber: '254711556677',
    fullName: 'Joyline Chepkemoi',
    campus: 'Egerton',
    isVerified: false,
    createdAt: '2026-09-12T13:10:00Z',
    subscribedService: 'Campus Escrow Insurance & Bounties',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-moi-07823',
    phoneNumber: '254733445566',
    fullName: 'Collins Mutua',
    campus: 'Moi',
    isVerified: true,
    createdAt: '2026-09-14T10:05:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-mmu-09123',
    phoneNumber: '254708778899',
    fullName: 'Agnes Mutindi',
    campus: 'MMU',
    isVerified: false,
    createdAt: '2026-09-17T18:30:00Z',
    subscribedService: 'Free Tier Explorer',
    subscriptionStatus: 'EXPIRED',
  }
];

export const INITIAL_SERVICE_METRICS: ServiceSubscriptionMetric[] = [
  {
    serviceId: 'srv-all-access',
    serviceName: '1-Semester All-Access Hustle Pass',
    priceKes: 130,
    subscriberCount: 248,
    revenueKes: 32240,
    description: 'Instant client phone unlock, AI qualification guides, and PDF expense exports.',
    category: 'Full Access Pass'
  },
  {
    serviceId: 'srv-ai-guides',
    serviceName: 'AI Screening Prompts & Guides',
    priceKes: 130,
    subscriberCount: 142,
    revenueKes: 18460,
    description: 'Specialized RLHF prompts, Sheng/Swahili grading rubric cheat sheets ($14–$20/hr).',
    category: 'AI Tooling'
  },
  {
    serviceId: 'srv-escrow-insurance',
    serviceName: 'Campus Escrow Insurance & Bounties',
    priceKes: 130,
    subscriberCount: 189,
    revenueKes: 24570,
    description: 'Zero-dispute Daraja STK escrow hold on student tasks and project bounties.',
    category: 'Escrow Security'
  },
  {
    serviceId: 'srv-sms-sync',
    serviceName: 'HELB & Statement Auto-Parser',
    priceKes: 130,
    subscriberCount: 116,
    revenueKes: 15080,
    description: 'Daily kibanda burn analysis and HELB semester runway survival calculator.',
    category: 'Runway Engine'
  }
];

export const INITIAL_GIGS: Gig[] = [
  {
    id: 'gig-escrow-001',
    posterId: 'usr-mmu-04289',
    posterName: 'Grace A. (MMU Hostel 3)',
    posterPhone: '254712345678',
    title: 'LaTeX Formatting & Code Debug for 4th Year Telecom Project',
    description: 'Need IEEE format alignment with 4 MATLAB signal graphs and bibliography in BibTeX. Ready to pay immediately via M-Pesa Escrow upon submission.',
    category: 'Tech & Design',
    rewardKes: 2500,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'MMU',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['LaTeX', 'MATLAB', 'IEEE Format'],
    platformName: 'Campus Escrow Till',
    deadline: 'Tomorrow, 5:00 PM',
    createdAt: '2026-09-20T14:30:00Z',
    applicantCount: 3,
  },
  {
    id: 'gig-fuzu-005',
    posterName: 'Safaricom Talent Pool via Fuzu',
    title: 'Junior Cyber Threat & NOC Student Intern (Attachment 2026/2027)',
    description: 'Industrial attachment opportunity at Safaricom HQ / Westlands. Daily stipend provided plus mentorship under Safaricom Security Operations Center.',
    category: 'Attachment & Internship',
    rewardKes: 25000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.fuzu.com/kenya/jobs/safaricom-cyber-threat-intern-2026',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Networking', 'Linux', 'Security+', 'NOC'],
    platformName: 'Fuzu Kenya',
    deadline: 'End of Month',
    createdAt: '2026-09-20T09:00:00Z',
    applicantCount: 310,
  },
  {
    id: 'gig-ai-002',
    posterName: 'Alignerr Global',
    title: 'Swahili & Sheng RLHF Prompt Evaluator (Remote)',
    description: 'Score bilingual English/Swahili chat model responses for cultural accuracy, Kenyan local context, and safety guidelines. Weekly direct M-Pesa / Wise payout.',
    category: 'AI Annotation',
    rewardKes: 18000,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://alignerr.com/apply/swahili-annotator',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Sheng / Swahili', 'English', 'Fact-Checking', 'LLM Evaluation'],
    platformName: 'Alignerr AI',
    qualificationGuide: 'Requires 20-min benchmark test. 80%+ pass rate qualifies for $14/hr rate batch.',
    createdAt: '2026-09-20T10:15:00Z',
    applicantCount: 142,
  },
  {
    id: 'gig-ai-004',
    posterName: 'DataAnnotation Tech',
    title: 'Python Coding Task Verification & Edge Case Generator',
    description: 'Write test cases, debug junior code blocks, and evaluate complexity analysis of Python scripts. Payout is $20.00/hr (~KSh 2,600/hr) with direct M-Pesa / PayPal converter.',
    category: 'AI Annotation',
    rewardKes: 32000,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://dataannotation.tech/coders',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Python', 'DSA', 'Unit Testing'],
    platformName: 'DataAnnotation.tech',
    qualificationGuide: 'Takes 45 mins. Solve 2 coding problems and explain code quality metrics.',
    createdAt: '2026-09-18T11:00:00Z',
    applicantCount: 89,
  },
  {
    id: 'gig-brighter-008',
    posterName: 'KCB Bank via BrighterMonday',
    title: 'FinTech Software Engineering Graduate Trainee & Attachment',
    description: 'Work with the digital payments engineering team in Upper Hill Nairobi building microservices and API gateways for mobile banking.',
    category: 'Attachment & Internship',
    rewardKes: 30000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.brightermonday.co.ke/job/fintech-graduate-trainee-software-engineer',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Java / Spring', 'PostgreSQL', 'Docker', 'REST APIs'],
    platformName: 'BrighterMonday',
    deadline: 'In 10 days',
    createdAt: '2026-09-20T15:00:00Z',
    applicantCount: 215,
  },
  {
    id: 'gig-escrow-003',
    posterName: 'Kevin Mwangi (UoN SRC Rep)',
    posterPhone: '254722987654',
    title: 'Physics & Calc II Revision Notes Transcription to Markdown',
    description: 'Transcribe 45 pages of handwritten lecture notes into crisp Markdown with KaTeX mathematical formulas. Payment held in campus escrow.',
    category: 'Campus Task',
    rewardKes: 1200,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'UoN',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Markdown', 'KaTeX', 'Speed Typing'],
    platformName: 'Campus Escrow Till',
    deadline: 'In 3 days',
    createdAt: '2026-09-19T18:00:00Z',
    applicantCount: 7,
  },
  {
    id: 'gig-escrow-006',
    posterName: 'Faith Chebet (JKUAT Hostel C)',
    posterPhone: '254701239841',
    title: 'Lab Report Proofreading & ChemSketch Molecule Diagrams',
    description: 'Need assistance drawing 6 organic reaction mechanisms in ChemSketch and checking grammar for Organic Chemistry II lab report.',
    category: 'Tutoring',
    rewardKes: 850,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'JKUAT',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Chemistry', 'ChemSketch', 'Proofreading'],
    platformName: 'Campus Escrow Till',
    deadline: 'Tomorrow morning',
    createdAt: '2026-09-20T16:00:00Z',
    applicantCount: 2,
  },
  {
    id: 'gig-ai-007',
    posterName: 'Mindrift / Toloka AI',
    title: 'AI Image Captioning & Local Kenyan Landmark Bounding Boxes',
    description: 'Label street views, matatus, local storefront signs, and urban infrastructure for autonomous driving and OCR models.',
    category: 'AI Annotation',
    rewardKes: 9500,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://mindrift.ai/tasks',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Attention to Detail', 'Image Tagging'],
    platformName: 'Mindrift',
    qualificationGuide: 'Short 10-question visual quiz. Smartphone touch screen friendly.',
    createdAt: '2026-09-20T12:00:00Z',
    applicantCount: 64,
  }
];

export const INITIAL_FINANCIAL_LOGS: FinancialLog[] = [
  {
    id: 'fin-001',
    userId: 'usr-mmu-04289',
    category: 'HELB',
    amount: 18500,
    transactionType: 'INCOME',
    description: 'HELB Semester Upkeep Disbursement',
    loggedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'fin-002',
    userId: 'usr-mmu-04289',
    category: 'Rent',
    amount: 6500,
    transactionType: 'EXPENSE',
    description: 'Hostel Rent 1st Installment',
    loggedAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'fin-003',
    userId: 'usr-mmu-04289',
    category: 'Kibanda',
    amount: 220,
    transactionType: 'EXPENSE',
    description: 'Lunch Kibanda (Ugali Sukuma + Beef)',
    loggedAt: '2026-09-20T13:00:00Z',
  },
  {
    id: 'fin-004',
    userId: 'usr-mmu-04289',
    category: 'Bundles',
    amount: 100,
    transactionType: 'EXPENSE',
    description: 'Safaricom 1GB 24hr Campus Bundle',
    loggedAt: '2026-09-20T16:45:00Z',
  },
  {
    id: 'fin-005',
    userId: 'usr-mmu-04289',
    category: 'SideHustle',
    amount: 2500,
    transactionType: 'INCOME',
    description: 'LaTeX Thesis Formatting Gig Bounty',
    loggedAt: '2026-09-18T19:20:00Z',
  }
];

export const KENYAN_MMF_FUNDS: MmfFund[] = [
  {
    id: 'mmf-etica',
    name: 'Etica Money Market Fund',
    dailyYieldPct: 0.0435,
    effectiveAnnualRatePct: 16.85,
    minInvestmentKes: 100,
    managementFeePct: 1.5,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [15.8, 16.1, 16.2, 16.4, 16.6, 16.75, 16.85],
  },
  {
    id: 'mmf-lofty',
    name: 'Lofty-Corban KES MMF',
    dailyYieldPct: 0.0425,
    effectiveAnnualRatePct: 16.40,
    minInvestmentKes: 1000,
    managementFeePct: 1.75,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [15.2, 15.6, 15.9, 16.1, 16.2, 16.35, 16.4],
  },
  {
    id: 'mmf-kuza',
    name: 'Kuza Asset Management MMF',
    dailyYieldPct: 0.0412,
    effectiveAnnualRatePct: 15.95,
    minInvestmentKes: 500,
    managementFeePct: 1.5,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [15.0, 15.3, 15.5, 15.7, 15.8, 15.9, 15.95],
  },
  {
    id: 'mmf-genafrica',
    name: 'GenAfrica Unit Trust MMF',
    dailyYieldPct: 0.0401,
    effectiveAnnualRatePct: 15.50,
    minInvestmentKes: 500,
    managementFeePct: 2.0,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [14.8, 15.0, 15.1, 15.25, 15.35, 15.45, 15.5],
  },
  {
    id: 'mmf-cic',
    name: 'CIC Money Market Fund',
    dailyYieldPct: 0.0375,
    effectiveAnnualRatePct: 14.50,
    minInvestmentKes: 5000,
    managementFeePct: 2.0,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [13.9, 14.1, 14.2, 14.3, 14.4, 14.45, 14.5],
  },
  {
    id: 'mmf-sanlam',
    name: 'Sanlam Kenya Pesa MMF',
    dailyYieldPct: 0.0368,
    effectiveAnnualRatePct: 14.25,
    minInvestmentKes: 2500,
    managementFeePct: 2.2,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [13.5, 13.8, 13.95, 14.05, 14.15, 14.2, 14.25],
  }
];
