import { Gig, MmfFund, FinancialLog, User, ServiceSubscriptionMetric } from '../types';

export const INITIAL_USER: User = {
  id: 'usr-mmu-04289',
  phoneNumber: '254712345678',
  fullName: 'Brian Kiprono',
  campus: 'MMU',
  isVerified: true,
  createdAt: '2026-09-01T08:00:00Z',
  subscribedService: '1-Semester All-Access Pass',
  subscriptionStatus: 'ACTIVE',
};

export const INITIAL_STUDENT_ACCOUNTS: User[] = [
  {
    id: 'usr-mmu-04289',
    phoneNumber: '254712345678',
    fullName: 'Brian Kiprono',
    campus: 'MMU',
    isVerified: true,
    createdAt: '2026-09-01T08:00:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-uon-08124',
    phoneNumber: '254722987654',
    fullName: 'Wanjiku Kamau',
    campus: 'UoN',
    isVerified: true,
    createdAt: '2026-09-03T11:20:00Z',
    subscribedService: 'AI Screening Prompts & Guides',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-jkuat-01938',
    phoneNumber: '254701239841',
    fullName: 'Dennis Omondi',
    campus: 'JKUAT',
    isVerified: true,
    createdAt: '2026-09-05T14:15:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-ku-05712',
    phoneNumber: '254798334455',
    fullName: 'Mercy Jebet',
    campus: 'KU',
    isVerified: false,
    createdAt: '2026-09-08T09:40:00Z',
    subscribedService: 'SMS Statement Sync & PDF Exporter',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-strath-02381',
    phoneNumber: '254740112233',
    fullName: 'Farouk Hassan',
    campus: 'Strathmore',
    isVerified: true,
    createdAt: '2026-09-10T16:50:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-egerton-03910',
    phoneNumber: '254711556677',
    fullName: 'Joyline Chepkemoi',
    campus: 'Egerton',
    isVerified: false,
    createdAt: '2026-09-12T13:10:00Z',
    subscribedService: 'Campus Escrow Insurance & Bounties',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-moi-07823',
    phoneNumber: '254733445566',
    fullName: 'Collins Mutua',
    campus: 'Moi',
    isVerified: true,
    createdAt: '2026-09-14T10:05:00Z',
    subscribedService: '1-Semester All-Access Pass',
    subscriptionStatus: 'ACTIVE',
  },
  {
    id: 'usr-mmu-09123',
    phoneNumber: '254708778899',
    fullName: 'Agnes Mutindi',
    campus: 'MMU',
    isVerified: false,
    createdAt: '2026-09-17T18:30:00Z',
    subscribedService: 'Free Tier Explorer',
    subscriptionStatus: 'EXPIRED',
  }
];

export const INITIAL_SERVICE_METRICS: ServiceSubscriptionMetric[] = [
  {
    serviceId: 'srv-all-access',
    serviceName: '1-Semester All-Access Hustle Pass',
    priceKes: 130,
    subscriberCount: 248,
    revenueKes: 32240,
    description: 'Instant client phone unlock, AI qualification guides, and PDF expense exports.',
    category: 'Full Access Pass'
  },
  {
    serviceId: 'srv-ai-guides',
    serviceName: 'AI Screening Prompts & Guides',
    priceKes: 130,
    subscriberCount: 142,
    revenueKes: 18460,
    description: 'Specialized RLHF prompts, Sheng/Swahili grading rubric cheat sheets ($14–$20/hr).',
    category: 'AI Tooling'
  },
  {
    serviceId: 'srv-escrow-insurance',
    serviceName: 'Campus Escrow Insurance & Bounties',
    priceKes: 130,
    subscriberCount: 189,
    revenueKes: 24570,
    description: 'Zero-dispute Daraja STK escrow hold on student tasks and project bounties.',
    category: 'Escrow Security'
  },
  {
    serviceId: 'srv-sms-sync',
    serviceName: 'HELB & Statement Auto-Parser',
    priceKes: 130,
    subscriberCount: 116,
    revenueKes: 15080,
    description: 'Daily kibanda burn analysis and HELB semester runway survival calculator.',
    category: 'Runway Engine'
  }
];

export const INITIAL_GIGS: Gig[] = [
  // 1. GLOBAL REMOTE - NO COUNTRY RESTRICTIONS (KENYA & WORLDWIDE ELIGIBLE)
  {
    id: 'gig-global-001',
    posterName: 'Alignerr Global AI Lab',
    title: 'Bilingual Sheng/Swahili & STEM LLM Reasoning Evaluator (Global Remote)',
    description: 'Score multi-turn generative AI responses for Kenyan local dialect nuances, STEM logical consistency, and factual precision. No country restriction. Weekly payout directly to M-Pesa / Bank ($15.00–$25.00/hr).',
    category: 'Global Remote',
    rewardUsd: 175,
    rewardKes: 22750,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.alignerr.com',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Swahili / Sheng', 'Logic Reasoning', 'Prompt Evaluation'],
    platformName: 'Alignerr AI',
    qualificationGuide: 'Quick 20-min benchmark assessment. Direct remote registration open globally.',
    createdAt: '2026-09-20T10:15:00Z',
    applicantCount: 248,
  },
  {
    id: 'gig-global-002',
    posterName: 'DataAnnotation.tech Global',
    title: 'Python & JavaScript Algorithm Code Verification Batch (Worldwide Remote)',
    description: 'Evaluate code quality, generate unit test edge cases, and rate AI programming responses. Open worldwide including Kenya with direct hourly compensation ($20.00–$40.00/hr, ~KSh 2,600–5,200/hr).',
    category: 'Global Remote',
    rewardUsd: 300,
    rewardKes: 39000,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.dataannotation.tech',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Python', 'JavaScript', 'Unit Testing', 'DSA'],
    platformName: 'DataAnnotation.tech',
    qualificationGuide: 'Pass the starter coding test. Works on any laptop worldwide.',
    createdAt: '2026-09-19T14:00:00Z',
    applicantCount: 195,
  },
  {
    id: 'gig-global-003',
    posterName: 'Outlier.ai / Scale AI',
    title: 'Multimodal AI Prompt & Creative Dialogue Rater (Global Remote)',
    description: 'Rank and refine chatbot conversations, analyze reasoning steps, and verify conversational coherence. Completely open to worldwide applicants with flexible hours and weekly payments.',
    category: 'AI Annotation',
    rewardUsd: 145,
    rewardKes: 18850,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://outlier.ai',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Fact-Checking', 'English Proficiency', 'Critical Thinking'],
    platformName: 'Outlier.ai',
    qualificationGuide: 'Takes 15 mins to complete profile and start onboarding tasks.',
    createdAt: '2026-09-20T12:00:00Z',
    applicantCount: 312,
  },
  {
    id: 'gig-global-004',
    posterName: 'Mindrift AI Freelance',
    title: 'AI Tutor & Multidisciplinary Academic Subject Matter Expert (Global Remote)',
    description: 'Review AI-generated explanations across Mathematics, Computer Science, Literature, and Economics. Open to college students worldwide ($12–$22/hr).',
    category: 'Global Remote',
    rewardUsd: 125,
    rewardKes: 16250,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://mindrift.ai',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Academic Writing', 'Subject Tutoring', 'Quality Assurance'],
    platformName: 'Mindrift',
    qualificationGuide: 'Short subject assessment quiz upon signup.',
    createdAt: '2026-09-20T08:30:00Z',
    applicantCount: 140,
  },
  {
    id: 'gig-global-005',
    posterName: 'OneForma by Centific',
    title: 'Multilingual Audio Transcription & Linguistic Annotation (Worldwide)',
    description: 'Transcribe audio recordings and validate speech synthesis datasets. Accessible worldwide from smartphone or laptop with zero geographical lock.',
    category: 'Global Remote',
    rewardUsd: 95,
    rewardKes: 12350,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.oneforma.com',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Transcription', 'Swahili', 'Audio Grading'],
    platformName: 'OneForma',
    qualificationGuide: 'Smartphone-friendly audio certification test.',
    createdAt: '2026-09-18T16:00:00Z',
    applicantCount: 88,
  },
  {
    id: 'gig-global-006',
    posterName: 'RemoteOK Worldwide',
    title: 'Junior Remote Frontend QA Tester & Bug Hunter (Worldwide Remote)',
    description: 'Perform cross-browser compatibility testing, responsive layout verification, and log reproducible GitHub issues for international tech startups.',
    category: 'Global Remote',
    rewardUsd: 350,
    rewardKes: 45500,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://remoteok.com',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['QA Testing', 'HTML/CSS', 'Bug Reports', 'Chrome DevTools'],
    platformName: 'RemoteOK',
    createdAt: '2026-09-20T07:45:00Z',
    applicantCount: 420,
  },
  {
    id: 'gig-global-007',
    posterName: 'Clickworker Global',
    title: 'AI Micro-tasks, Search Engine Relevance & Data Categorization',
    description: 'Perform web research verification, OCR text correction, and image validation batches. Instant entry with worldwide student access and weekly cashout.',
    category: 'Global Remote',
    rewardUsd: 65,
    rewardKes: 8450,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.clickworker.com',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Web Research', 'Data Entry', 'Attention to Detail'],
    platformName: 'Clickworker',
    qualificationGuide: 'Immediate entry upon email confirmation and basic assessment.',
    createdAt: '2026-09-19T09:20:00Z',
    applicantCount: 165,
  },

  // 2. KENYAN JOBS WITH 100% REMOTE / HYBRID APPLICATION
  {
    id: 'gig-kenya-001',
    posterName: 'Fuzu Kenya Remote Portal',
    title: 'Remote Junior Web Developer & Tech Support Specialist (Kenyan Applicants)',
    description: 'Kenyan tech firm hiring university students & graduates for remote front-end bug resolution, client portal maintenance, and ticketing support. Full remote application via Fuzu Kenya.',
    category: 'Kenyan Remote',
    rewardUsd: 270,
    rewardKes: 35000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.fuzu.com/kenya',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['JavaScript', 'React', 'HTML/CSS', 'Technical Support'],
    platformName: 'Fuzu Kenya',
    deadline: 'End of Month',
    createdAt: '2026-09-20T11:00:00Z',
    applicantCount: 380,
  },
  {
    id: 'gig-kenya-002',
    posterName: 'BrighterMonday Kenya Remote Hub',
    title: 'Remote Virtual Assistant & Digital Data Entry Intern (Kenya Remote)',
    description: 'Assist Nairobi-based e-commerce and logistics companies with catalog inventory updates, customer WhatsApp inquiries, and Excel bookkeeping. Allows remote work from any Kenyan campus.',
    category: 'Kenyan Remote',
    rewardUsd: 170,
    rewardKes: 22000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.brightermonday.co.ke/jobs',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Excel', 'Customer Support', 'Data Entry', 'WhatsApp Business'],
    platformName: 'BrighterMonday',
    deadline: 'In 12 days',
    createdAt: '2026-09-20T13:30:00Z',
    applicantCount: 290,
  },
  {
    id: 'gig-kenya-003',
    posterName: 'MyJobMag Kenya Remote',
    title: 'Remote Content Writer & SEO Copywriting Intern (Kenyan University Students)',
    description: 'Draft search-optimized campus lifestyle articles, scholarship roundups, and product reviews for leading East African digital publications. Submit portfolio directly online.',
    category: 'Kenyan Remote',
    rewardUsd: 140,
    rewardKes: 18000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.myjobmag.co.ke',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['SEO Copywriting', 'Content Writing', 'Research', 'WordPress'],
    platformName: 'MyJobMag Kenya',
    deadline: 'In 2 weeks',
    createdAt: '2026-09-19T17:15:00Z',
    applicantCount: 210,
  },
  {
    id: 'gig-kenya-004',
    posterName: 'Safaricom Talent Ecosystem via Fuzu',
    title: 'Junior Cyber Threat & Digital Solutions Attachment (Hybrid/Remote Option)',
    description: 'Industrial attachment opportunity at Safaricom with remote learning modules and Westlands HQ mentoring. Monthly stipend provided plus M-Pesa digital systems exposure.',
    category: 'Attachment & Internship',
    rewardUsd: 195,
    rewardKes: 25000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.fuzu.com/kenya',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Networking', 'Linux', 'Security+', 'NOC'],
    platformName: 'Fuzu Kenya',
    deadline: 'End of Month',
    createdAt: '2026-09-20T09:00:00Z',
    applicantCount: 450,
  },

  // 3. CAMPUS ESCROW BOUNTIES (MMU, UON, KU, JKUAT, STRATHMORE, EGERTON, MOI)
  {
    id: 'gig-escrow-001',
    posterId: 'usr-mmu-04289',
    posterName: 'Grace A. (MMU Hostel 3)',
    posterPhone: '254712345678',
    title: 'LaTeX Formatting & Code Debug for 4th Year Telecom Project',
    description: 'Need IEEE format alignment with 4 MATLAB signal graphs and bibliography in BibTeX. Ready to pay immediately via Escrow upon submission.',
    category: 'Tech & Design',
    rewardUsd: 20,
    rewardKes: 2600,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'MMU',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['LaTeX', 'MATLAB', 'IEEE Format'],
    platformName: 'Campus Escrow Till',
    deadline: 'Tomorrow, 5:00 PM',
    createdAt: '2026-09-20T14:30:00Z',
    applicantCount: 3,
  },
  {
    id: 'gig-escrow-003',
    posterName: 'Kevin Mwangi (UoN SRC Rep)',
    posterPhone: '254722987654',
    title: 'Physics & Calc II Revision Notes Transcription to Markdown',
    description: 'Transcribe 45 pages of handwritten lecture notes into crisp Markdown with KaTeX mathematical formulas. Payment held in campus escrow.',
    category: 'Campus Task',
    rewardUsd: 10,
    rewardKes: 1300,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'UoN',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Markdown', 'KaTeX', 'Speed Typing'],
    platformName: 'Campus Escrow Till',
    deadline: 'In 3 days',
    createdAt: '2026-09-19T18:00:00Z',
    applicantCount: 7,
  },
  {
    id: 'gig-escrow-006',
    posterName: 'Faith Chebet (JKUAT Hostel C)',
    posterPhone: '254701239841',
    title: 'Lab Report Proofreading & ChemSketch Molecule Diagrams',
    description: 'Need assistance drawing 6 organic reaction mechanisms in ChemSketch and checking grammar for Organic Chemistry II lab report.',
    category: 'Tutoring',
    rewardUsd: 8,
    rewardKes: 1040,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'JKUAT',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Chemistry', 'ChemSketch', 'Proofreading'],
    platformName: 'Campus Escrow Till',
    deadline: 'Tomorrow morning',
    createdAt: '2026-09-20T16:00:00Z',
    applicantCount: 2,
  }
];

export const INITIAL_FINANCIAL_LOGS: FinancialLog[] = [
  {
    id: 'fin-001',
    userId: 'usr-mmu-04289',
    category: 'HELB',
    amount: 18500,
    transactionType: 'INCOME',
    description: 'HELB Semester Upkeep Disbursement',
    loggedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'fin-002',
    userId: 'usr-mmu-04289',
    category: 'Rent',
    amount: 6500,
    transactionType: 'EXPENSE',
    description: 'Hostel Rent 1st Installment',
    loggedAt: '2026-09-02T10:30:00Z',
  },
  {
    id: 'fin-003',
    userId: 'usr-mmu-04289',
    category: 'Kibanda',
    amount: 220,
    transactionType: 'EXPENSE',
    description: 'Lunch Kibanda (Ugali Sukuma + Beef)',
    loggedAt: '2026-09-20T13:00:00Z',
  },
  {
    id: 'fin-004',
    userId: 'usr-mmu-04289',
    category: 'Bundles',
    amount: 100,
    transactionType: 'EXPENSE',
    description: 'Safaricom 1GB 24hr Campus Bundle',
    loggedAt: '2026-09-20T16:45:00Z',
  },
  {
    id: 'fin-005',
    userId: 'usr-mmu-04289',
    category: 'SideHustle',
    amount: 2500,
    transactionType: 'INCOME',
    description: 'LaTeX Thesis Formatting Gig Bounty',
    loggedAt: '2026-09-18T19:20:00Z',
  }
];

export const KENYAN_MMF_FUNDS: MmfFund[] = [
  {
    id: 'mmf-etica',
    name: 'Etica Money Market Fund',
    dailyYieldPct: 0.0435,
    effectiveAnnualRatePct: 16.85,
    minInvestmentKes: 100,
    managementFeePct: 1.5,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [15.8, 16.1, 16.2, 16.4, 16.6, 16.75, 16.85],
  },
  {
    id: 'mmf-lofty',
    name: 'Lofty-Corban KES MMF',
    dailyYieldPct: 0.0425,
    effectiveAnnualRatePct: 16.40,
    minInvestmentKes: 1000,
    managementFeePct: 1.75,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [15.2, 15.6, 15.9, 16.1, 16.2, 16.35, 16.4],
  },
  {
    id: 'mmf-kuza',
    name: 'Kuza Asset Management MMF',
    dailyYieldPct: 0.0412,
    effectiveAnnualRatePct: 15.95,
    minInvestmentKes: 500,
    managementFeePct: 1.5,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [15.0, 15.3, 15.5, 15.7, 15.8, 15.9, 15.95],
  },
  {
    id: 'mmf-genafrica',
    name: 'GenAfrica Unit Trust MMF',
    dailyYieldPct: 0.0401,
    effectiveAnnualRatePct: 15.50,
    minInvestmentKes: 500,
    managementFeePct: 2.0,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [14.8, 15.0, 15.1, 15.25, 15.35, 15.45, 15.5],
  },
  {
    id: 'mmf-cic',
    name: 'CIC Money Market Fund',
    dailyYieldPct: 0.0375,
    effectiveAnnualRatePct: 14.50,
    minInvestmentKes: 5000,
    managementFeePct: 2.0,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [13.9, 14.1, 14.2, 14.3, 14.4, 14.45, 14.5],
  },
  {
    id: 'mmf-sanlam',
    name: 'Sanlam Kenya Pesa MMF',
    dailyYieldPct: 0.0368,
    effectiveAnnualRatePct: 14.25,
    minInvestmentKes: 2500,
    managementFeePct: 2.2,
    riskProfile: 'Low',
    withholdingTaxPct: 15,
    sparklineData: [13.5, 13.8, 13.95, 14.05, 14.15, 14.2, 14.25],
  }
];
