import { Gig, MmfFund, FinancialLog, User, ServiceSubscriptionMetric } from '../types';

export const INITIAL_USER: User = {
  id: 'usr-guest',
  phoneNumber: '',
  fullName: '',
  campus: 'MMU',
  isVerified: false,
  createdAt: '2026-09-01T08:00:00Z',
  subscribedService: 'Free Tier (Unpaid)',
  subscriptionStatus: 'PENDING',
};

export const INITIAL_STUDENT_ACCOUNTS: User[] = [];

export const INITIAL_SERVICE_METRICS: ServiceSubscriptionMetric[] = [
  {
    serviceId: 'srv-all-access',
    serviceName: '1-Semester All-Access Hustle Pass',
    priceKes: 130,
    subscriberCount: 0,
    revenueKes: 0,
    description: 'Instant client phone unlock, AI qualification guides, and PDF expense exports.',
    category: 'Full Access Pass'
  },
  {
    serviceId: 'srv-ai-guides',
    serviceName: 'AI Screening Prompts & Guides',
    priceKes: 130,
    subscriberCount: 0,
    revenueKes: 0,
    description: 'Specialized RLHF prompts, Sheng/Swahili grading rubric cheat sheets ($14–$20/hr).',
    category: 'AI Tooling'
  },
  {
    serviceId: 'srv-escrow-insurance',
    serviceName: 'Campus Escrow Insurance & Bounties',
    priceKes: 130,
    subscriberCount: 0,
    revenueKes: 0,
    description: 'Zero-dispute Daraja STK escrow hold on student tasks and project bounties.',
    category: 'Escrow Security'
  },
  {
    serviceId: 'srv-sms-sync',
    serviceName: 'HELB & Statement Auto-Parser',
    priceKes: 130,
    subscriberCount: 0,
    revenueKes: 0,
    description: 'Daily kibanda burn analysis and HELB semester runway survival calculator.',
    category: 'Runway Engine'
  },
  {
    serviceId: 'srv-gemini-family',
    serviceName: 'Gemini Pro / Advanced AI (Google Family Access)',
    priceKes: 200,
    subscriberCount: 0,
    revenueKes: 0,
    description: 'Join Google Family for full Gemini Advanced/Pro access (1M-2M context, deep reasoning, code execution, thesis assistant).',
    category: 'AI Pro Access'
  }
];

export const INITIAL_GIGS: Gig[] = [
  // 1. GLOBAL REMOTE - NO COUNTRY RESTRICTIONS (KENYA & WORLDWIDE ELIGIBLE)
  {
    id: 'gig-global-001',
    posterName: 'Alignerr Global AI Lab',
    title: 'Bilingual Sheng/Swahili & STEM LLM Reasoning Evaluator (Global Remote)',
    description: 'Score multi-turn generative AI responses for Kenyan local dialect nuances, STEM logical consistency, and factual precision. No country restriction. Weekly payout directly to M-Pesa / Bank ($15.00–$25.00/hr).',
    category: 'Global Remote',
    rewardUsd: 175,
    rewardKes: 22750,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.alignerr.com',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Swahili / Sheng', 'Logic Reasoning', 'Prompt Evaluation'],
    platformName: 'Alignerr AI',
    qualificationGuide: 'Quick 20-min benchmark assessment. Direct remote registration open globally.',
    createdAt: '2026-09-20T10:15:00Z',
    applicantCount: 248,
    isFeatured: true,
  },
  {
    id: 'gig-global-002',
    posterName: 'DataAnnotation.tech Global',
    title: 'Python & JavaScript Algorithm Code Verification Batch (Worldwide Remote)',
    description: 'Evaluate code quality, generate unit test edge cases, and rate AI programming responses. Open worldwide including Kenya with direct hourly compensation ($20.00–$40.00/hr, ~KSh 2,600–5,200/hr).',
    category: 'Global Remote',
    rewardUsd: 300,
    rewardKes: 39000,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.dataannotation.tech',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Python', 'JavaScript', 'Unit Testing', 'DSA'],
    platformName: 'DataAnnotation.tech',
    qualificationGuide: 'Pass the starter coding test. Works on any laptop worldwide.',
    createdAt: '2026-09-19T14:00:00Z',
    applicantCount: 195,
    isFeatured: true,
  },
  {
    id: 'gig-global-003',
    posterName: 'Outlier.ai / Scale AI',
    title: 'Multimodal AI Prompt & Creative Dialogue Rater (Global Remote)',
    description: 'Rank and refine chatbot conversations, analyze reasoning steps, and verify conversational coherence. Completely open to worldwide applicants with flexible hours and weekly payments.',
    category: 'AI Annotation',
    rewardUsd: 145,
    rewardKes: 18850,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://outlier.ai',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Fact-Checking', 'English Proficiency', 'Critical Thinking'],
    platformName: 'Outlier.ai',
    qualificationGuide: 'Takes 15 mins to complete profile and start onboarding tasks.',
    createdAt: '2026-09-20T12:00:00Z',
    applicantCount: 312,
  },
  {
    id: 'gig-global-004',
    posterName: 'Mindrift AI Freelance',
    title: 'AI Tutor & Multidisciplinary Academic Subject Matter Expert (Global Remote)',
    description: 'Review AI-generated explanations across Mathematics, Computer Science, Literature, and Economics. Open to college students worldwide ($12–$22/hr).',
    category: 'Global Remote',
    rewardUsd: 135,
    rewardKes: 17550,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://mindrift.ai',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Mathematics', 'Computer Science', 'Curriculum Review'],
    platformName: 'Mindrift AI',
    qualificationGuide: 'Pass subject qualification test. Flexible hours from Kenya.',
    createdAt: '2026-09-18T16:30:00Z',
    applicantCount: 160,
  },
  {
    id: 'gig-global-005',
    posterName: 'OneForma by Centific',
    title: 'Multilingual Audio Transcription & Micro-Task Engine (Worldwide)',
    description: 'Transcribe and annotate short voice recordings in English, Swahili, and local regional accents. No country restriction, weekly PayPal/Payoneer/Bank payout.',
    category: 'Global Remote',
    rewardUsd: 110,
    rewardKes: 14300,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.oneforma.com',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Audio Transcription', 'English', 'Swahili'],
    platformName: 'OneForma',
    qualificationGuide: 'Quick 10-min language verification quiz. Mobile friendly.',
    createdAt: '2026-09-19T09:00:00Z',
    applicantCount: 285,
  },
  {
    id: 'gig-global-006',
    posterName: 'Clickworker Global Workplace',
    title: 'Web Research, Search Engine Evaluation & Product Categorization (Worldwide)',
    description: 'Categorize e-commerce listings, test search query accuracy, and complete micro-data tasks. Flexible hourly pay ($10.00–$16.00/hr) with direct weekly payments.',
    category: 'Global Remote',
    rewardUsd: 95,
    rewardKes: 12350,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.clickworker.com',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Web Research', 'Attention to Detail', 'Data Entry'],
    platformName: 'Clickworker',
    qualificationGuide: 'Short assessment for UHRS platform access. Open worldwide.',
    createdAt: '2026-09-17T11:45:00Z',
    applicantCount: 340,
  },
  {
    id: 'gig-global-007',
    posterName: 'RemoteOK Global Tech',
    title: 'Junior React & Tailwind Front-End Component Developer (Worldwide Remote)',
    description: 'Build responsive Next.js/Tailwind landing page sections and component libraries for remote startups. Direct contract compensation ($350/milestone).',
    category: 'Global Remote',
    rewardUsd: 350,
    rewardKes: 45500,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://remoteok.com',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['React', 'Next.js', 'Tailwind CSS', 'TypeScript'],
    platformName: 'RemoteOK',
    qualificationGuide: 'Submit GitHub portfolio or recent code samples for review.',
    createdAt: '2026-09-18T18:00:00Z',
    applicantCount: 142,
  },

  // 2. KENYAN REMOTE OPPORTUNITIES
  {
    id: 'gig-ke-001',
    posterName: 'Fuzu Kenya Remote Portal',
    title: 'Remote Social Media Community Moderator & Content Creator (Kenya Remote)',
    description: 'Curate daily student tech community updates, moderate Discord and Telegram channels, and draft Twitter/X threads for Nairobi fintech startups.',
    category: 'Kenyan Remote',
    rewardUsd: 190,
    rewardKes: 25000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.fuzu.com/kenya',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Social Media', 'Canva', 'Community Management'],
    platformName: 'Fuzu Kenya',
    deadline: 'In 5 days',
    createdAt: '2026-09-20T08:00:00Z',
    applicantCount: 112,
  },
  {
    id: 'gig-ke-002',
    posterName: 'BrighterMonday Kenya Remote',
    title: 'Remote Junior Technical Writer & Documentation Intern (Kenya Remote)',
    description: 'Write beginner-friendly developer tutorials, API documentation, and how-to guides for Kenyan software companies. Flexible hours suitable for undergrads.',
    category: 'Kenyan Remote',
    rewardUsd: 230,
    rewardKes: 30000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.brightermonday.co.ke/jobs',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Technical Writing', 'Markdown', 'APIs', 'Research'],
    platformName: 'BrighterMonday',
    deadline: 'In 8 days',
    createdAt: '2026-09-19T15:20:00Z',
    applicantCount: 88,
  },
  {
    id: 'gig-ke-003',
    posterName: 'MyJobMag Kenya Portal',
    title: 'Remote Customer Support & WhatsApp Engagement Assistant (Kenya Remote)',
    description: 'Handle customer inquiries, respond to WhatsApp business catalog orders, and maintain CRM ticket logs for an e-commerce distributor.',
    category: 'Kenyan Remote',
    rewardUsd: 170,
    rewardKes: 22000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.myjobmag.co.ke',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Customer Service', 'WhatsApp Business', 'Typing Speed'],
    platformName: 'MyJobMag',
    deadline: 'In 12 days',
    createdAt: '2026-09-18T13:10:00Z',
    applicantCount: 175,
  },

];

export const KENYAN_MMF_FUNDS: MmfFund[] = [
  {
    id: 'mmf-etica',
    name: 'Etica Wealth Money Market Fund',
    dailyYieldPct: 0.0435,
    effectiveAnnualRatePct: 16.85,
    minInvestmentKes: 100,
    managementFeePct: 1.5,
    withholdingTaxPct: 15,
    riskProfile: 'Low',
    sparklineData: [15.8, 16.1, 16.3, 16.2, 16.5, 16.7, 16.85],
  },
  {
    id: 'mmf-sanlam',
    name: 'Sanlam Investments MMF',
    dailyYieldPct: 0.0398,
    effectiveAnnualRatePct: 15.20,
    minInvestmentKes: 500,
    managementFeePct: 1.2,
    withholdingTaxPct: 15,
    riskProfile: 'Low',
    sparklineData: [14.4, 14.7, 14.9, 15.0, 15.1, 15.15, 15.20],
  },
  {
    id: 'mmf-kuza',
    name: 'Kuza Asset Management MMF',
    dailyYieldPct: 0.0392,
    effectiveAnnualRatePct: 15.05,
    minInvestmentKes: 500,
    managementFeePct: 1.3,
    withholdingTaxPct: 15,
    riskProfile: 'Low',
    sparklineData: [14.2, 14.5, 14.7, 14.9, 15.0, 15.02, 15.05],
  },
  {
    id: 'mmf-ncba',
    name: 'NCBA Unit Trust MMF',
    dailyYieldPct: 0.0360,
    effectiveAnnualRatePct: 13.80,
    minInvestmentKes: 1000,
    managementFeePct: 2.0,
    withholdingTaxPct: 15,
    riskProfile: 'Low',
    sparklineData: [13.2, 13.4, 13.5, 13.6, 13.7, 13.75, 13.80],
  },
  {
    id: 'mmf-cic',
    name: 'CIC Money Market Fund',
    dailyYieldPct: 0.0352,
    effectiveAnnualRatePct: 13.45,
    minInvestmentKes: 1000,
    managementFeePct: 2.0,
    withholdingTaxPct: 15,
    riskProfile: 'Low',
    sparklineData: [13.0, 13.1, 13.2, 13.3, 13.4, 13.42, 13.45],
  },
  {
    id: 'mmf-britam',
    name: 'Britam Money Market Fund',
    dailyYieldPct: 0.0345,
    effectiveAnnualRatePct: 13.15,
    minInvestmentKes: 1000,
    managementFeePct: 1.8,
    withholdingTaxPct: 15,
    riskProfile: 'Low',
    sparklineData: [12.8, 12.9, 13.0, 13.05, 13.1, 13.12, 13.15],
  },
];

export const INITIAL_FINANCIAL_LOGS: FinancialLog[] = [];
