import { useState, useEffect } from 'react';
import { 
  User, 
  Gig, 
  FinancialLog, 
  Subscription, 
  MpesaTransaction, 
  NetworkCondition, 
  CampusName,
  ServiceSubscriptionMetric 
} from '../types';
import { 
  INITIAL_USER, 
  INITIAL_GIGS, 
  INITIAL_FINANCIAL_LOGS, 
  INITIAL_STUDENT_ACCOUNTS, 
  INITIAL_SERVICE_METRICS 
} from './mockData';

const STORAGE_KEYS = {
  USER: 'campushustle_user',
  GIGS: 'campushustle_gigs',
  FINANCES: 'campushustle_finances',
  SUBSCRIPTION: 'campushustle_subscription',
  TRANSACTIONS: 'campushustle_transactions',
  NETWORK: 'campushustle_network',
  STUDENTS: 'campushustle_students',
  SERVICES: 'campushustle_services',
  IS_LOGGED_IN: 'campushustle_is_logged_in',
};

// Pool of dynamic tasks that periodically launch automatically across Kenyan campuses
const LIVE_UPCOMING_TASKS: Omit<Gig, 'id' | 'createdAt' | 'applicantCount'>[] = [
  {
    posterName: 'Scale AI Global Remote',
    title: 'Kenyan Sheng & Multilingual Dialogue Quality Benchmarking (Worldwide)',
    description: 'Review generative AI dialogue transcripts for authentic Kenyan street syntax, regional vocabulary, and contextual nuances. Weekly payout direct to M-Pesa / Bank ($15.00/hr).',
    category: 'Global Remote',
    rewardKes: 19500,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://outlier.ai',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Sheng Fluency', 'Swahili', 'AI Evaluation'],
    platformName: 'Outlier.ai',
    qualificationGuide: 'Takes 15 mins. Smartphone friendly assessment.',
  },
  {
    posterName: 'Alignerr Global',
    title: 'Legal & Constitutional Law AI Reasoning Evaluation Batch (Global Remote)',
    description: 'Evaluate legal case summaries generated by LLMs for statutory precision and precedent citation accuracy. Open to law students worldwide ($18.00–$25.00/hr).',
    category: 'Global Remote',
    rewardKes: 24000,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.alignerr.com',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Law', 'Constitutional Law', 'Fact Checking'],
    platformName: 'Alignerr AI',
    qualificationGuide: 'Requires basic legal reasoning test. Remote onboarding.',
  },
  {
    posterName: 'Fuzu Kenya Remote Portal',
    title: 'Remote Digital Marketing & Social Community Moderator (Kenya Remote)',
    description: 'Manage community engagement, moderate student developer Discord forums, and schedule promotional campaigns for Kenyan startups remotely.',
    category: 'Kenyan Remote',
    rewardKes: 26000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.fuzu.com/kenya',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Community Management', 'Social Media', 'Content Moderation'],
    platformName: 'Fuzu Kenya',
    deadline: 'In 10 days',
  },
  {
    posterName: 'BrighterMonday Kenya Remote',
    title: 'Remote Junior Data Analyst & PowerBI Dashboard Intern (Kenya Remote)',
    description: 'Build automated weekly sales dashboards in PowerBI and Excel for regional supply chain distributors. Full remote attachment option.',
    category: 'Kenyan Remote',
    rewardKes: 28000,
    escrowStatus: 'UNFUNDED',
    originType: 'SCRAPED',
    externalApplyUrl: 'https://www.brightermonday.co.ke/jobs',
    campus: 'ALL',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['PowerBI', 'Excel', 'Data Analysis', 'SQL'],
    platformName: 'BrighterMonday',
    deadline: 'In 2 weeks',
  },
  {
    posterName: 'OneForma by Centific',
    title: 'Smartphone Audio Speech Validation & Sheng Dialect Grading (Worldwide)',
    description: 'Listen to short speech clips and score pronunciation accuracy. Zero country restrictions, smartphone touch-screen friendly.',
    category: 'Global Remote',
    rewardKes: 11500,
    escrowStatus: 'HELD',
    originType: 'EXTERNAL_PARTNER',
    externalApplyUrl: 'https://www.oneforma.com',
    campus: 'ALL',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Audio Validation', 'Swahili', 'Linguistics'],
    platformName: 'OneForma',
  },
  {
    posterName: 'Grace Wangari (MMU Engineering)',
    title: 'Arduino IoT Soil Moisture Sensor Circuit Schematic & Code',
    description: 'Need assistance wiring ESP32 with capacitive soil sensor and writing microPython telemetry script for Agriculture IoT project.',
    category: 'Tech & Design',
    rewardKes: 3200,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'MMU',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['ESP32', 'MicroPython', 'Circuit Design'],
    deadline: 'Within 24 hours',
  },
  {
    posterName: 'Emmanuel Kiprono (UoN Main)',
    title: 'SPSS Regression & Data Visualization for Economics Thesis',
    description: 'Clean survey responses from 120 respondents, run multilinear regression models, and export APA-standard tables with interpretation.',
    category: 'Campus Task',
    rewardKes: 2800,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'UoN',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['SPSS', 'Statistics', 'APA Tables'],
    deadline: 'In 2 days',
  },
  {
    posterName: 'Victor Otieno (JKUAT Juja)',
    title: 'Flutter Mobile UI State Management Refactoring (Provider/Bloc)',
    description: 'Help refactor existing campus food delivery mobile app prototype to clean Bloc architecture with offline Hive caching.',
    category: 'Tech & Design',
    rewardKes: 4800,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'JKUAT',
    deviceRequirement: 'LAPTOP_REQUIRED',
    skills: ['Flutter', 'Dart', 'Bloc Pattern'],
    deadline: 'In 3 days',
  },
  {
    posterName: 'Mercy Achieng (KU Nyayo)',
    title: 'Academic Journal Paper Proofreading & APA 7th Referencing',
    description: 'Check grammar, citation cross-references, and in-text citations for 18-page Environmental Science research draft.',
    category: 'Tutoring',
    rewardKes: 1400,
    escrowStatus: 'HELD',
    originType: 'INTERNAL_ESCROW',
    campus: 'KU',
    deviceRequirement: 'SMARTPHONE_OK',
    skills: ['Proofreading', 'APA 7th', 'Academic Writing'],
    deadline: 'Tomorrow evening',
  }
];

export interface TaskToastNotification {
  id: string;
  title: string;
  rewardKes: number;
  campus: string;
  launchedAt: string;
}

export class CampusHustleStore {
  private static instance: CampusHustleStore;
  
  isLoggedIn: boolean = false;
  user: User = INITIAL_USER;
  gigs: Gig[] = INITIAL_GIGS;
  finances: FinancialLog[] = INITIAL_FINANCIAL_LOGS;
  subscription: Subscription | null = null;
  transactions: MpesaTransaction[] = [];
  network: NetworkCondition = 'FAST_4G';
  students: User[] = INITIAL_STUDENT_ACCOUNTS;
  services: ServiceSubscriptionMetric[] = INITIAL_SERVICE_METRICS;
  
  // Real-time automatic task update engine
  isAutoUpdating: boolean = true;
  lastTaskLaunchedAt: string = new Date().toISOString();
  nextAutoUpdateSeconds: number = 25;
  taskPoolIndex: number = 0;
  latestTaskToast: TaskToastNotification | null = null;
  
  listeners: Set<() => void> = new Set();
  private autoUpdateTimer: NodeJS.Timeout | null = null;
  private countdownTimer: NodeJS.Timeout | null = null;

  private constructor() {
    if (typeof window !== 'undefined') {
      this.loadFromStorage();
      this.startAutoTaskEngine();
    }
  }

  static getInstance(): CampusHustleStore {
    if (!CampusHustleStore.instance) {
      CampusHustleStore.instance = new CampusHustleStore();
    }
    return CampusHustleStore.instance;
  }

  subscribe(listener: () => void) {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }

  private notify() {
    if (typeof window !== 'undefined') {
      this.saveToStorage();
    }
    this.listeners.forEach((l) => l());
  }

  private loadFromStorage() {
    try {
      const storedUser = localStorage.getItem(STORAGE_KEYS.USER);
      if (storedUser) this.user = JSON.parse(storedUser);

      const storedGigs = localStorage.getItem(STORAGE_KEYS.GIGS);
      if (storedGigs) {
        const parsed: Gig[] = JSON.parse(storedGigs);
        if (Array.isArray(parsed) && parsed.length > 0) {
          // Sanitize old broken URLs to reliable verified roots
          const sanitized = parsed.map((g) => {
            let url = g.externalApplyUrl;
            if (url) {
              if (url.includes('alignerr.com')) url = 'https://www.alignerr.com';
              else if (url.includes('outlier.ai')) url = 'https://outlier.ai';
              else if (url.includes('dataannotation.tech')) url = 'https://www.dataannotation.tech';
              else if (url.includes('fuzu.com')) url = 'https://www.fuzu.com/kenya';
              else if (url.includes('brightermonday.co.ke')) url = 'https://www.brightermonday.co.ke/jobs';
              else if (url.includes('mindrift.ai')) url = 'https://mindrift.ai';
              else if (url.includes('oneforma.com')) url = 'https://www.oneforma.com';
              else if (url.includes('clickworker.com')) url = 'https://www.clickworker.com';
              else if (url.includes('remoteok.com')) url = 'https://remoteok.com';
              else if (url.includes('myjobmag.co.ke')) url = 'https://www.myjobmag.co.ke';
            }
            return { ...g, externalApplyUrl: url };
          });

          // Merge any missing global / kenyan remote gigs from INITIAL_GIGS
          const existingIds = new Set(sanitized.map((g) => g.id));
          const missingGigs = INITIAL_GIGS.filter((g) => !existingIds.has(g.id));
          this.gigs = [...missingGigs, ...sanitized];
        }
      } else {
        this.gigs = INITIAL_GIGS;
      }

      const storedFinances = localStorage.getItem(STORAGE_KEYS.FINANCES);
      if (storedFinances) this.finances = JSON.parse(storedFinances);

      const storedSub = localStorage.getItem(STORAGE_KEYS.SUBSCRIPTION);
      if (storedSub) this.subscription = JSON.parse(storedSub);

      const storedTxs = localStorage.getItem(STORAGE_KEYS.TRANSACTIONS);
      if (storedTxs) this.transactions = JSON.parse(storedTxs);

      const storedNet = localStorage.getItem(STORAGE_KEYS.NETWORK);
      if (storedNet) this.network = storedNet as NetworkCondition;

      const storedStudents = localStorage.getItem(STORAGE_KEYS.STUDENTS);
      if (storedStudents) this.students = JSON.parse(storedStudents);

      const storedServices = localStorage.getItem(STORAGE_KEYS.SERVICES);
      if (storedServices) this.services = JSON.parse(storedServices);

      const storedLoggedIn = localStorage.getItem(STORAGE_KEYS.IS_LOGGED_IN);
      if (storedLoggedIn) this.isLoggedIn = storedLoggedIn === 'true';
    } catch (e) {
      console.error('Error loading from local storage', e);
    }
  }

  private saveToStorage() {
    try {
      localStorage.setItem(STORAGE_KEYS.USER, JSON.stringify(this.user));
      localStorage.setItem(STORAGE_KEYS.GIGS, JSON.stringify(this.gigs));
      localStorage.setItem(STORAGE_KEYS.FINANCES, JSON.stringify(this.finances));
      localStorage.setItem(STORAGE_KEYS.SUBSCRIPTION, JSON.stringify(this.subscription));
      localStorage.setItem(STORAGE_KEYS.TRANSACTIONS, JSON.stringify(this.transactions));
      localStorage.setItem(STORAGE_KEYS.NETWORK, this.network);
      localStorage.setItem(STORAGE_KEYS.STUDENTS, JSON.stringify(this.students));
      localStorage.setItem(STORAGE_KEYS.SERVICES, JSON.stringify(this.services));
      localStorage.setItem(STORAGE_KEYS.IS_LOGGED_IN, String(this.isLoggedIn));
    } catch (e) {
      console.error('Error saving to local storage', e);
    }
  }

  // --- Auto-updating Task System ---
  startAutoTaskEngine() {
    if (this.countdownTimer) clearInterval(this.countdownTimer);

    this.countdownTimer = setInterval(() => {
      if (!this.isAutoUpdating) return;

      if (this.nextAutoUpdateSeconds <= 1) {
        this.nextAutoUpdateSeconds = 25;
        this.injectNewLiveTask();
      } else {
        this.nextAutoUpdateSeconds -= 1;
        this.notify();
      }
    }, 1000);
  }

  toggleAutoUpdate() {
    this.isAutoUpdating = !this.isAutoUpdating;
    this.notify();
  }

  triggerManualTaskLaunch() {
    this.nextAutoUpdateSeconds = 25;
    this.injectNewLiveTask();
  }

  injectNewLiveTask() {
    const template = LIVE_UPCOMING_TASKS[this.taskPoolIndex % LIVE_UPCOMING_TASKS.length];
    this.taskPoolIndex += 1;

    const launchedIso = new Date().toISOString();
    const newTask: Gig = {
      ...template,
      id: `gig-live-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      createdAt: launchedIso,
      applicantCount: 0,
    };

    // Prepend to live gigs list
    this.gigs = [newTask, ...this.gigs];
    this.lastTaskLaunchedAt = launchedIso;
    
    // Set toast notification
    this.latestTaskToast = {
      id: newTask.id,
      title: newTask.title,
      rewardKes: newTask.rewardKes,
      campus: newTask.campus || 'ALL',
      launchedAt: launchedIso,
    };

    this.notify();

    // Auto dismiss toast after 6 seconds
    setTimeout(() => {
      if (this.latestTaskToast?.id === newTask.id) {
        this.latestTaskToast = null;
        this.notify();
      }
    }, 6000);
  }

  dismissTaskToast() {
    this.latestTaskToast = null;
    this.notify();
  }

  // --- Standard User and Store Methods ---
  setCampus(campus: CampusName) {
    this.user = { ...this.user, campus };
    this.notify();
  }

  setNetwork(net: NetworkCondition) {
    this.network = net;
    this.notify();
  }

  addFinancialLog(log: Omit<FinancialLog, 'id' | 'loggedAt' | 'userId'>) {
    const newLog: FinancialLog = {
      id: `fin-${Date.now()}-${Math.floor(Math.random() * 1000)}`,
      userId: this.user.id,
      loggedAt: new Date().toISOString(),
      ...log,
    };
    this.finances = [newLog, ...this.finances];
    this.notify();
    return newLog;
  }

  addGig(gig: Omit<Gig, 'id' | 'createdAt' | 'applicantCount'>) {
    const launchedIso = new Date().toISOString();
    const newGig: Gig = {
      id: `gig-user-${Date.now()}`,
      createdAt: launchedIso,
      applicantCount: 0,
      ...gig,
    };
    this.gigs = [newGig, ...this.gigs];
    this.lastTaskLaunchedAt = launchedIso;
    
    this.latestTaskToast = {
      id: newGig.id,
      title: newGig.title,
      rewardKes: newGig.rewardKes,
      campus: newGig.campus || 'ALL',
      launchedAt: launchedIso,
    };

    this.notify();
    return newGig;
  }

  updateEscrowStatus(gigId: string, status: Gig['escrowStatus']) {
    this.gigs = this.gigs.map((g) => (g.id === gigId ? { ...g, escrowStatus: status } : g));
    this.notify();
  }

  applyToGig(gigId: string) {
    this.gigs = this.gigs.map((g) => (g.id === gigId ? { ...g, applicantCount: g.applicantCount + 1 } : g));
    this.notify();
  }

  addStudentAccount(fullName: string, phoneNumber: string, campus: CampusName, service: string = '1-Semester All-Access Pass') {
    const newStudent: User = {
      id: `usr-${campus.toLowerCase()}-${Math.floor(10000 + Math.random() * 90000)}`,
      phoneNumber,
      fullName,
      campus,
      isVerified: true,
      createdAt: new Date().toISOString(),
      subscribedService: service,
      subscriptionStatus: 'ACTIVE',
    };

    this.students = [newStudent, ...this.students];
    
    this.services = this.services.map((srv) => {
      if (srv.serviceName.toLowerCase().includes(service.toLowerCase()) || service.toLowerCase().includes(srv.serviceName.toLowerCase())) {
        return {
          ...srv,
          subscriberCount: srv.subscriberCount + 1,
          revenueKes: srv.revenueKes + srv.priceKes,
        };
      }
      return srv;
    });

    this.notify();
    return newStudent;
  }

  authenticateUser(fullName: string, emailOrPhone: string, campus: CampusName, isGoogle: boolean = false): User {
    this.isLoggedIn = true;
    const existing = this.students.find(
      (s) => s.phoneNumber === emailOrPhone || s.fullName.toLowerCase() === fullName.toLowerCase() || (s.email && s.email.toLowerCase() === emailOrPhone.toLowerCase())
    );

    if (existing) {
      this.user = existing;
      this.notify();
      return existing;
    }

    const newUser: User = {
      id: `usr-${campus.toLowerCase()}-${Math.floor(10000 + Math.random() * 90000)}`,
      phoneNumber: emailOrPhone.includes('@') ? `2547${Math.floor(10000000 + Math.random() * 89999999)}` : emailOrPhone,
      email: emailOrPhone.includes('@') ? emailOrPhone : undefined,
      fullName: fullName || (isGoogle ? 'Verified Google Scholar' : 'Campus Hustler'),
      campus,
      isVerified: true,
      createdAt: new Date().toISOString(),
      subscribedService: '1-Semester All-Access Hustle Pass',
      subscriptionStatus: 'ACTIVE',
    };

    this.user = newUser;
    this.students = [newUser, ...this.students];

    const expires = new Date();
    expires.setDate(expires.getDate() + 120);
    this.subscription = {
      id: `sub-auth-${Date.now()}`,
      userId: newUser.id,
      amount: 130,
      mpesaReceipt: `GOOG${Math.floor(10000000 + Math.random() * 90000000)}`,
      status: 'ACTIVE',
      serviceType: 'SEMESTER_ALL_ACCESS',
      expiresAt: expires.toISOString(),
      createdAt: new Date().toISOString(),
    };

    this.services = this.services.map((srv) => {
      if (srv.serviceId === 'srv-all-access') {
        return {
          ...srv,
          subscriberCount: srv.subscriberCount + 1,
          revenueKes: srv.revenueKes + 130,
        };
      }
      return srv;
    });

    this.notify();
    return newUser;
  }

  async initiateDarajaStk(phoneNumber: string, amount: number = 130, purpose: MpesaTransaction['purpose'] = 'SUBSCRIPTION_PASS') {
    const checkoutRequestId = `ws_CO_${Date.now()}_${Math.floor(Math.random() * 100000)}`;
    const merchantRequestId = `MR_${Date.now()}`;
    
    const newTx: MpesaTransaction = {
      id: `tx-${Date.now()}`,
      checkoutRequestId,
      merchantRequestId,
      phoneNumber,
      amount,
      purpose,
      status: 'PENDING',
      createdAt: new Date().toISOString(),
    };

    this.transactions = [newTx, ...this.transactions];
    this.notify();

    return newTx;
  }

  resolveMpesaCallback(checkoutRequestId: string, success: boolean, receiptNumber?: string) {
    const receipt = receiptNumber || `SLK${Math.floor(10000000 + Math.random() * 90000000)}KE`;
    
    this.transactions = this.transactions.map((tx) => {
      if (tx.checkoutRequestId === checkoutRequestId) {
        return {
          ...tx,
          status: success ? 'SUCCESS' : 'FAILED',
          resultCode: success ? 0 : 1032,
          resultDesc: success ? 'The service request is processed successfully.' : 'Request cancelled by user.',
          mpesaReceipt: success ? receipt : undefined,
        };
      }
      return tx;
    });

    if (success) {
      const tx = this.transactions.find((t) => t.checkoutRequestId === checkoutRequestId);
      if (tx && tx.purpose === 'SUBSCRIPTION_PASS') {
        const expires = new Date();
        expires.setDate(expires.getDate() + 120);
        this.subscription = {
          id: `sub-${Date.now()}`,
          userId: this.user.id,
          amount: tx.amount,
          mpesaReceipt: receipt,
          status: 'ACTIVE',
          serviceType: 'SEMESTER_ALL_ACCESS',
          expiresAt: expires.toISOString(),
          createdAt: new Date().toISOString(),
        };

        this.services = this.services.map((srv) => {
          if (srv.serviceId === 'srv-all-access') {
            return {
              ...srv,
              subscriberCount: srv.subscriberCount + 1,
              revenueKes: srv.revenueKes + tx.amount,
            };
          }
          return srv;
        });
      }
    }

    this.notify();
  }

  ADMIN_EMAIL = 'liliankavengi502@gmail.com';
  theme: 'light' | 'dark' = 'light';

  setTheme(newTheme: 'light' | 'dark') {
    this.theme = newTheme;
    this.notify();
  }

  isAdmin(): boolean {
    return this.user?.email === this.ADMIN_EMAIL;
  }

  loginAsAdmin(): User {
    this.isLoggedIn = true;
    const adminUser: User = {
      id: 'usr-admin-lilian',
      fullName: 'Lilian Kavengi',
      email: this.ADMIN_EMAIL,
      phoneNumber: '254712999502',
      campus: 'MMU',
      isVerified: true,
      createdAt: '2026-09-01T00:00:00Z',
      subscribedService: 'Platform Super Administrator',
      subscriptionStatus: 'ACTIVE',
    };

    this.user = adminUser;
    
    if (!this.students.some(s => s.email === this.ADMIN_EMAIL)) {
      this.students = [adminUser, ...this.students];
    }

    this.notify();
    return adminUser;
  }

  logout() {
    this.isLoggedIn = false;
    this.user = INITIAL_USER;
    this.notify();
  }

  hasActivePass(): boolean {
    if (!this.subscription) return false;
    if (this.subscription.status !== 'ACTIVE') return false;
    return new Date(this.subscription.expiresAt) > new Date();
  }

  resetDemo() {
    this.user = INITIAL_USER;
    this.gigs = INITIAL_GIGS;
    this.finances = INITIAL_FINANCIAL_LOGS;
    this.subscription = null;
    this.transactions = [];
    this.network = 'FAST_4G';
    this.students = INITIAL_STUDENT_ACCOUNTS;
    this.services = INITIAL_SERVICE_METRICS;
    this.notify();
  }
}

// Global hook
export function useCampusStore() {
  const store = CampusHustleStore.getInstance();
  const [, setTick] = useState(0);

  useEffect(() => {
    return store.subscribe(() => setTick((t) => t + 1));
  }, [store]);

  return store;
}

// Timestamp formatting helper
export function formatLaunchTime(isoString: string): { relative: string; exact: string; timeOnly: string } {
  try {
    const date = new Date(isoString);
    const now = new Date();
    const diffSeconds = Math.max(0, Math.floor((now.getTime() - date.getTime()) / 1000));

    let relative = 'Just now';
    if (diffSeconds < 45) {
      relative = 'Just now';
    } else if (diffSeconds < 90) {
      relative = '1 min ago';
    } else if (diffSeconds < 3600) {
      relative = `${Math.floor(diffSeconds / 60)} mins ago`;
    } else if (diffSeconds < 86400) {
      const hours = Math.floor(diffSeconds / 3600);
      relative = hours === 1 ? '1 hour ago' : `${hours} hours ago`;
    } else {
      const days = Math.floor(diffSeconds / 86400);
      relative = days === 1 ? 'Yesterday' : `${days} days ago`;
    }

    const timeOnly = date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
    const exact = `${date.toLocaleDateString([], { month: 'short', day: 'numeric' })} at ${timeOnly}`;

    return { relative, exact, timeOnly };
  } catch (e) {
    return { relative: 'Recently', exact: isoString, timeOnly: '' };
  }
}
