import { RawJobPayload } from '../normalizers/jobNormalizer';

export const AI_LABS_METADATA = {
  sourceId: 'src-ai-labs-global',
  sourceName: 'AI Training & Annotation Labs',
  sourceType: 'AI_LAB' as const,
  officialUrl: 'https://www.alignerr.com',
  termsUrl: 'https://www.alignerr.com/terms',
  ingestionMethod: 'API' as const,
  verifiedDomain: 'alignerr.com',
  trustScore: 98,
};

export async function fetchAiEvaluationJobs(): Promise<RawJobPayload[]> {
  return [
    {
      sourceId: 'src-alignerr-ai',
      sourceJobId: 'alg-2026-001',
      title: 'Bilingual Sheng/Swahili & STEM LLM Reasoning Evaluator (Global Remote)',
      companyName: 'Alignerr Global AI Lab',
      description: 'Score multi-turn generative AI responses for Kenyan local dialect nuances, STEM logical consistency, and factual precision. No country restriction. Weekly payout directly to M-Pesa / Bank ($15.00–$25.00/hr).',
      category: 'AI Annotation',
      rewardUsd: 175,
      rewardKes: 22750,
      externalApplyUrl: 'https://www.alignerr.com',
      location: 'Remote (Kenya & Worldwide Eligible)',
      skills: ['Swahili / Sheng', 'Logic Reasoning', 'Prompt Evaluation'],
      platformName: 'Alignerr AI',
      deviceRequirement: 'LAPTOP_REQUIRED',
      qualificationGuide: 'Quick 20-min benchmark assessment. Direct remote registration open globally.',
      isKenyaEligible: true,
      isStudentAccepted: true,
    },
    {
      sourceId: 'src-dataannotation-tech',
      sourceJobId: 'dat-2026-002',
      title: 'Python & JavaScript Algorithm Code Verification Batch (Worldwide Remote)',
      companyName: 'DataAnnotation.tech Global',
      description: 'Evaluate code quality, generate unit test edge cases, and rate AI programming responses. Open worldwide including Kenya with direct hourly compensation ($20.00–$40.00/hr, ~KSh 2,600–5,200/hr).',
      category: 'AI Annotation',
      rewardUsd: 300,
      rewardKes: 39000,
      externalApplyUrl: 'https://www.dataannotation.tech',
      location: 'Worldwide Remote (Kenya eligible)',
      skills: ['Python', 'JavaScript', 'Unit Testing', 'DSA'],
      platformName: 'DataAnnotation.tech',
      deviceRequirement: 'LAPTOP_REQUIRED',
      qualificationGuide: 'Pass the starter coding test. Works on any laptop worldwide.',
      isKenyaEligible: true,
      isStudentAccepted: true,
    },
    {
      sourceId: 'src-outlier-ai',
      sourceJobId: 'out-2026-003',
      title: 'Multimodal AI Prompt & Creative Dialogue Rater (Global Remote)',
      companyName: 'Outlier.ai / Scale AI',
      description: 'Review AI-generated text, audio transcripts, and creative writing prompts against strict safety and hallucination rubrics. Flexible hours on laptop or tablet ($14.00–$18.00/hr).',
      category: 'AI Annotation',
      rewardUsd: 140,
      rewardKes: 18200,
      externalApplyUrl: 'https://outlier.ai',
      location: 'Remote (Worldwide)',
      skills: ['Critical Reading', 'Fact Checking', 'Creative Writing'],
      platformName: 'Outlier.ai',
      deviceRequirement: 'LAPTOP_REQUIRED',
      qualificationGuide: 'Interactive rubric onboarding. Payouts processed every Tuesday.',
      isKenyaEligible: true,
      isStudentAccepted: true,
    },
    {
      sourceId: 'src-oneforma-ai',
      sourceJobId: 'onf-2026-004',
      title: 'Smartphone Audio Speech Validation & Sheng Dialect Grading (Worldwide)',
      companyName: 'OneForma by Centific',
      description: 'Listen to short speech clips and score pronunciation accuracy. Zero country restrictions, smartphone touch-screen friendly. Weekly micro-bounty settlements.',
      category: 'Microtask',
      rewardUsd: 90,
      rewardKes: 11700,
      externalApplyUrl: 'https://www.oneforma.com',
      location: 'Worldwide Remote (Smartphone OK)',
      skills: ['Audio Validation', 'Swahili / Sheng', 'Listening Skills'],
      platformName: 'OneForma',
      deviceRequirement: 'SMARTPHONE_OK',
      qualificationGuide: 'Takes 10 mins. Pass audio quality headset test.',
      isKenyaEligible: true,
      isStudentAccepted: true,
    }
  ];
}
